version: 0.2

env:
  variables:
    IMAGE_REPO_NAME: bimba-train
    IMAGE_TAG: latest
    DLC_REGISTRY: 763104351884      # AWS DLC account ID

phases:
  pre_build:
    commands:
      - echo "Logging in to ECR ..."
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REPO_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${IMAGE_REPO_NAME}

      # login to *your* registry (push target)
      - "aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login -u AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"

      # login to AWS DLC registry (base images)
      - "aws ecr get-login-password --region ${AWS_DEFAULT_REGION} | docker login -u AWS --password-stdin ${DLC_REGISTRY}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"

      - "aws ecr describe-repositories --repository-names ${IMAGE_REPO_NAME} || aws ecr create-repository --repository-name ${IMAGE_REPO_NAME}"

  build:
    commands:
      - echo "Building Docker image ..."
      - "docker build -t ${IMAGE_REPO_NAME}:${IMAGE_TAG} ."
      - "docker tag ${IMAGE_REPO_NAME}:${IMAGE_TAG} ${REPO_URI}:${IMAGE_TAG}"

  post_build:
    commands:
      - echo "Pushing image to ECR ..."
      - "docker push ${REPO_URI}:${IMAGE_TAG}"
      - "echo Image URI: ${REPO_URI}:${IMAGE_TAG}"

artifacts:
  files: []
